AllCops:
  NewCops: enable
  Exclude:
    - db/**/*
    - config/**/*
    - bin/**/*
    - config.ru
    - Rakefile
    - vendor/**/*
    - spec/**/*
    - Gemfile
  TargetRubyVersion: 3.1.2

  SuggestExtensions: false

# Metrics/MethodLength:
#   Max: 25

Metrics/BlockLength:
  Enabled: false

Style/Documentation:
  Enabled: false
Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

# Metrics/CyclomaticComplexity:
#   Max: 10

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false